[package]
name = "adventofcode2020"
version = "0.1.0"
authors = ["Timo <timo@mondido.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0.1"
itertools = "0.10.0"
nalgebra = "0.24.0"
